name: Lint

on:
  push:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8
        run: python -m pip install --upgrade pip flake8

      - name: Run flake8
        run: flake8
